---
- name: Configure DNS filtering and firewall rules
  hosts: all
  become: true
  tasks:

    - name: Install dnsmasq
      apt:
        name: dnsmasq
        state: present

    - name: Enable dnsmasq in Networking.conf
      lineinfile:
        path: /etc/NetworkManager/NetworkManager.conf
        regexp: '^dns='
        line: 'dns=dnsmasq'
        state: present

    - name: Modify dnsmasq.conf
      lineinfile:
        path: /etc/dnsmasq.conf
        regexp: '^#?conf-dir=/etc/dnsmasq.d/,.*$'
        line: 'conf-dir=/etc/dnsmasq.d/,*.conf'
        state: present

    - name: Copying dnsmasq config file
      ansible.builtin.copy:
        src: ./dnsmasq.conf
        dest: /etc/dnsmasq.d/dns_filter.conf
        mode: "620"

    - name: Restart dnsmasq service
      service:
        name: dnsmasq
        state: restarted

    - name: Add nftables rule for input DNS traffic on 5353
      command: >
        nft add rule inet basic_configuration input udp dport 5353 accept

    - name: Add nftables rule for forwarding DNS traffic on 5353
      command: >
        nft add rule inet basic_configuration forward udp dport 5353 accept 

    - name: Add nftables rule to redirect DNS traffic on port 53 to 5353
      command: >
        nft add rule inet basic_configuration prerouting udp dport 53 redirect to 5353
