---
- name: Configure dnsmasq, NetworkManager and nftables firewall rules
  hosts: all
  become: true
  tasks:

  # Étape 1 : Désactivation de systemd-resolved
  - name: Désactiver systemd-resolved
    shell: |
      sudo systemctl unmask systemd-resolved
      sudo systemctl enable systemd-resolved
      sudo systemctl start systemd-resolved
      sudo systemctl stop systemd-resolved
      sudo systemctl disable systemd-resolved
      sudo systemctl mask systemd-resolved

  # Étape 2 : Modification de /etc/resolv.conf
  - name: Supprimer et recréer le lien symbolique de resolv.conf
    shell: |
      sudo rm /etc/resolv.conf
      sudo ln -s /run/NetworkManager/resolv.conf /etc/resolv.conf

  # Étape 3 : Configuration de dnsmasq dans NetworkManager
  - name: Ajouter dnsmasq comme serveur DNS dans NetworkManager
    lineinfile:
      path: /etc/NetworkManager/NetworkManager.conf
      line: 'dns=dnsmasq'
      state: present

  # Étape 4 : Copie de la configuration dnsmasq
  - name: Copier le fichier dnsmasq.conf dans /etc/NetworkManager/dnsmasq.d/
    copy:
      src: ./dnsmasq.conf
      dest: /etc/NetworkManager/dnsmasq.d/dnsmasq.conf

  # Étape 5 : Redémarrer NetworkManager
  - name: Redémarrer NetworkManager pour appliquer la configuration
    service:
      name: NetworkManager
      state: restarted

  # Étape 6 : Configuration des règles nftablesn
  - name: Ajouter des règles nftables pour autoriser le DNS
    shell: |
      sudo nft add rule inet basic_configuration input udp dport 53 accept
      sudo nft add rule inet basic_configuration input tcp dport 53 accept
      sudo nft add rule inet basic_configuration forward udp dport 53 accept
      sudo nft add rule inet basic_configuration forward tcp dport 53 accept


