---
- name: Configure SSH settings on server
  hosts: all
  become: yes
  tasks:
    - name : Install OpenSSH server
      ansible.builtin.package:
        name: openssh-server
        state: present
        
    - name: Copying sshd config 
      ansible.builtin.copy:
        src: ./sshd_config
        dest: /etc/ssh/sshd_config
        mode: "620"

    - name: SSH is enabled and started
      ansible.builtin.systemd:
        name: ssh
        state: started
        enabled: true