---
- import_playbook: ./ssh/ssh.yml

- import_playbook: ./wireguard/wireguard.yml

- import_playbook: ./fail2ban/fail2ban.yml

- import_playbook: ./lynis/lynis.yml

- import_playbook: ./rkhunter/rkhunter.yml



- import_playbook: ./nftables/nftables.yml

- import_playbook: ./geoblocking/geoblocking.yml

- import_playbook: ./dnsmasq/dnsmasq.yml

- import_playbook: ./ids/ids.yml



