---
- import_playbook: ./ssh/ssh.yaml

- import_playbook: ./nftables/nftables.yaml
- import_playbook: ./fail2ban/fail2ban.yaml
- import_playbook: ./geoblocking/geoblocking.yml

- import_playbook: ./wireguard/wireguard.yaml
- import_playbook: ./ids/ids.yaml

- import_playbook: ./lynis/lynis.yaml
- import_playbook: ./rkhunter/rkhunter.yaml
- import_playbook: ./crontab/crontab.yaml

- import_playbook: ./dnsmasq/dnsmasq.yml
