---
- hosts: all
  become: yes
  tasks:
    - name: Install rkhunter
      apt:
        name: rkhunter
        state: present
        update_cache: yes

    - name: Update rkhunter
      command: rkhunter --update
