---
- name: Configure nftables
  hosts: all
  become: yes
  tasks:
    - name: Install nftables
      ansible.builtin.package:
        name: nftables
        state: present

    - name: Copying nftables config file
      ansible.builtin.copy:
        src: ./nftables.conf
        dest: /etc/nftables.conf
        mode: "620"

    - name: Nftables is enabled and started
      ansible.builtin.systemd:
        name: nftables
        state: started
        enabled: true

    - name: Reload nftables
      ansible.builtin.systemd:
        name: nftables
        state: reloaded
